### ISSUE TITLE
[en-eo] Add Number 1 to 100 for Esperanto

### ISSUE THREAD

**Issue by wboka** [wboka/learnxinyminutes-language-edition#10]
**Is your feature request related to a problem? Please describe.**

The number for English to Esperanto only go from 1 to 5.

**Describe the solution you'd like**

I want to see the numbers from 1 to 100.

**Describe alternatives you've considered**

If a common pattern is found, please leave numbers out. For example the numbers in German have a repeating pattern from 20 to 100.

**Additional context**

Contributors with knowledge of Esperanto helpful but not required. Feel free to use a translation tool if you want 👍

**Comment by Yaswanth899** [comment]
@wboka I can work with JSON but i am not familiar with Ruby can i contribute.!? 
i think English to Esperanto numbers data is enough for wards my contribution..

**Comment by wboka** [comment]
Absolutely! If you just want to make changes to the numbers.json file you can pull request to the en-eo branch in my repo and I’ll test it for you. Thanks for the help.

**Comment by Yaswanth899** [comment]
sure i'll get back you when I am Done.
thank you.
