### ISSUE TITLE
Discussion: formal/informal, masculine/feminine

### ISSUE THREAD

**Issue by Menelion** [wboka/learnxinyminutes-language-edition#38]
Hi Wayne @wboka,
In many languages there are some differences absent in English:

1. **Formality**. In old, I'd say, auld times, in English also there was a pronoun *thou* to address one single person informally. What do we do with those: add as translated alternatives, mark in parentheses, some other ideas?
2. **Grammatical gender**. In some languages (French, Slavic languages) phrases like *I'm tired* sound differently when the *I* in question is a man or a woman (there seem to be no accepted linguistic norms for non-binary people yet). Again, what do we do with these?

Thanks!

**Comment by wboka** [comment]
@Menelion,

Let's go with translated alternatives for both scenarios. See English to Spanish example below.

```json
{
  "original": "the cat",
  "translated": "el gato",
  "translated_alternatives": ["la gata"]
}
```
