### ISSUE TITLE
[multiple langs] Numbers, greetings, what else?

### ISSUE THREAD

**Issue by Menelion** [wboka/learnxinyminutes-language-edition#7]
Hi Wayne,  
I'm really passionated by your idea of creating this repo. As a translator by education and speaker of quite a number of languages, I would like to contribute. However, I still a bit don't understand some points:

- Numbers. I see numbers only from 1 to 5. Is it your intention or should I expand?
- Greetings, numbers. What else would you like to see in the repo?

Thanks for your effort!

**Comment by wboka** [comment]
Hello Andre,

What do you see on the website right now is simply a starting Prototype to see if there is interest. I would like to see the the numbers section expanded up to 100 and anything passed that would be fine. I’m working on some ideas for sections to make each language combination similar.

What languages can you translate?

Let me know if you have some ideas or if you need me to translate this in another language for you.

Thanks for reaching out.

**Comment by Menelion** [comment]
Thanks Wayne, then I'll send PRs to expand sections and I'll add new languages :). I speak English, French, German, Russian, Ukrainian, and I have also some knowledge in Spanish, Swedish, Belarusian and Esperanto. And a wee bit of Greek and Turkish, also :). So I believe I could help you in this.
